# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "811393b7d422d2293c25c22e504446ad"
name = "ai-theme-guide"
handle = "ai-theme-guide"
application_url = "https://filter-generates-skins-problem.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "renergii.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_product_listings,write_customers,write_discounts,write_products"

[auth]
redirect_urls = [
  "https://filter-generates-skins-problem.trycloudflare.com/auth/callback",
  "https://filter-generates-skins-problem.trycloudflare.com/auth/shopify/callback",
  "https://filter-generates-skins-problem.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
